# Copyright (c) 2026 Ibrahim Yalcinsoy. Alle Rechte vorbehalten.
"""Englische Oberflaechentexte: deutscher Quelltext -> Englisch (siehe polderfit.sprache)."""

EN: dict[str, str] = {
    '\n\nFehler:\n': '\n\nErrors:\n',
    '\nKriterien: ': '\nCriteria: ',
    '\nnoch nicht gefittet – Grenzen ziehen fittet diese Frequenz': '\nnot fitted yet – dragging the limits fits this frequency',
    '   ↳ M{0} · Dip {1} von {2}': '   ↳ M{0} · dip {1} of {2}',
    '  (problematisch)': '  (problematic)',
    '  Phase: {0}': '  Phase: {0}',
    ' (Mode M{0})': ' (mode M{0})',
    ' (M{0})': ' (M{0})',
    ' (verworfen)': ' (rejected)',
    ' GHz': ' GHz',
    ' Punkte': ' points',
    ' T': ' T',
    ' gefittet (je Mode nur im Korridor).': ' fitted (each mode only inside its corridor).',
    ' mT': ' mT',
    ' {0} nur je Mode.': ' {0} only per mode.',
    ' · gelb = Trennlinie': ' · yellow = separator',
    ' · noch ≈ {0:.0f} s': ' · ≈ {0:.0f} s left',
    ' · {0} Dips': ' · {0} dips',
    ' · {0} Fits': ' · {0} fits',
    ' – Korridore und Einstellungen bleiben erhalten.': ' – corridors and settings are kept.',
    ' – Mode {0}': ' – mode {0}',
    ' – Moden {0}; je Frequenz wird zwischen den Dips hart getrennt und jeder Dip einzeln gefittet.': ' – modes {0}; at each frequency the dips are separated strictly and each dip is fitted on its own.',
    ' – alle Moden': ' – all modes',
    ' – gilt ab dem nächsten Korridor-Fit.': ' – applies from the next corridor fit.',
    ' – gilt entlang der Mode ({0} Stützstelle(n))': ' – applies along the mode ({0} node(s))',
    '#{0} · Mode {1}:  f = {2:7.3f} GHz,  B_res = {3:.4f} T  (nur Kittel/LLG dieser Mode)': '#{0} · mode {1}:  f = {2:7.3f} GHz,  B_res = {3:.4f} T  (Kittel/LLG of this mode only)',
    '#{0}:  f = {1:7.3f} GHz,  B_res = {2:.4f} T': '#{0}:  f = {1:7.3f} GHz,  B_res = {2:.4f} T',
    '%p %': '%p %',
    '&Ansicht': '&View',
    '&Bearbeiten': '&Edit',
    '&Datei': '&File',
    '&Einstellungen': '&Settings',
    '&Hilfe': '&Help',
    '&Speichern / Export': '&Save / Export',
    '(nicht zugeordnet)': '(not assigned)',
    ', Anzahl automatisch (BIC)': ', number automatic (BIC)',
    ', Breite {0} Punkte': ', width {0} points',
    ', CSV deutsch': ', CSV German format',
    ', jede {0}. Frequenz': ', 1 in {0} frequencies',
    ', nur gefittete': ', fitted only',
    ', {0} Punkt(e) nur je Mode ausgeschlossen': ', {0} point(s) excluded for one mode only',
    '. Frequenz': ' frequencies',
    '1 = jede Frequenz; 10 = jede 10. Frequenz (Linescan).': '1 = every frequency; 10 = every 10th frequency (linescan).',
    '1 = jeder Feldpunkt; 10 = jeder 10. Punkt je Linescan.': '1 = every field point; 10 = every 10th point per linescan.',
    '; Fit: {0}': '; fit: {0}',
    '; zusätzlich alle *_2, *_3 … Spalten': '; plus all *_2, *_3 … columns',
    '</span>': '</span>',
    "<b style='font-size:16px'>{0}</b><br>Breitband-FMR-Auswertung": "<b style='font-size:16px'>{0}</b><br>Broadband FMR analysis",
    '<b>{0}</b> – Profil: {1}, Layout: {2}': '<b>{0}</b> – profile: {1}, layout: {2}',
    '<b>{0}</b> – bitte die Kanaele den Rollen zuordnen. Pflichtrollen sind mit * markiert.': '<b>{0}</b> – please assign the channels to the roles. Required roles are marked with *.',
    "<h3 style='color:{0}'>Mode {1} – {2} Punkte</h3>": "<h3 style='color:{0}'>Mode {1} – {2} points</h3>",
    '<i>Gruppe</i>': '<i>Group</i>',
    '<i>Kanal</i>': '<i>Channel</i>',
    '<i>Rolle</i>': '<i>Role</i>',
    "<p style='color:{0};font-size:11px'>Kittel-/LLG-Fit {1} (umschaltbar: Strg+P). Unsicherheiten der Parameter: im Export.</p>": "<p style='color:{0};font-size:11px'>Kittel/LLG fit {1} (switchable: Ctrl+P). Parameter uncertainties: in the export.</p>",
    '<p><b>Punkte:</b> {0} verwendet, {1} Ausreißer ausgeblendet': '<p><b>Points:</b> {0} used, {1} outliers hidden',
    '<p>Keine Fits vorhanden.</p>': '<p>No fits available.</p>',
    '<span style="color:#C0392B">{0}</span>': '<span style="color:#C0392B">{0}</span>',
    '<span style="color:{0}">': '<span style="color:{0}">',
    '<span style="color:{0}">{1} - {2} von {3} Linescans, ~{4} Feldpunkte je Linescan.</span>': '<span style="color:{0}">{1} - {2} of {3} linescans, ~{4} field points per linescan.</span>',
    '<{0}>LLG (Dämpfung)</{0}><ul><li>α = {1}</li><li>µ₀ΔH<sub>0</sub> (inhomogen) = {2} mT = {3} T</li><li>R² = {4:.5f}</li></ul>': '<{0}>LLG (damping)</{0}><ul><li>α = {1}</li><li>µ₀ΔH<sub>0</sub> (inhomogeneous) = {2} mT = {3} T</li><li>R² = {4:.5f}</li></ul>',
    'Abbrechen': 'Cancel',
    'Abbruch angefordert – der laufende Schritt wird noch beendet, bisherige Ergebnisse bleiben erhalten.': 'Cancellation requested – the current step is still finished, results so far are kept.',
    'Ableitung entlang {0}': 'Derivative along {0}',
    'Achse:': 'Axis:',
    'Achsenindex des Referenz-Slices (0 = erster, −1 = letzter Punkt).\nDer zugehörige Feld-/Frequenzwert steht darunter.': 'Axis index of the reference slice (0 = first, −1 = last point).\nThe corresponding field/frequency value is shown below.',
    'Achtung: derselbe Kanal ist mehreren Rollen zugeordnet: ': 'Warning: the same channel is assigned to several roles: ',
    'Aktivität / Hintergrund': 'Activity / background',
    'Aktivitäts- und Protokoll-Panel ein-/ausblenden.': 'Show/hide the activity and log panel.',
    'Aktuelle Ansicht des Farbplots mit Overlays (PNG/PDF/SVG).': 'Current view of the color plot with overlays (PNG/PDF/SVG).',
    'Aktuelle Ansicht des Farbplots samt Fit-Punkten, Zonen und Geraden.': 'Current view of the color plot including fit points, zones and lines.',
    'Aktuellen Fit als gut bestätigen': 'Confirm current fit as good',
    'Aktuellen Fit als problematisch markieren': 'Mark current fit as problematic',
    'Aktuellen Fit automatisch bewerten (Kriterien)': 'Rate current fit automatically (criteria)',
    'Aktuellen Fit ignorieren / wieder aufnehmen': 'Ignore / re-include current fit',
    'Alle': 'All',
    'Alle Bewertungen auf automatisch': 'All ratings to automatic',
    'Alle Bewertungen auf automatisch zurücksetzen': 'Reset all ratings to automatic',
    'Alle Bewertungen sind bereits automatisch.': 'All ratings are already automatic.',
    'Alle Fitparameter (B_res und ΔH in T und mT, α, Amplitude/Phase, komplexe Amplitude, Offsets, Gütemaße, Status) + Kittel/LLG + Einstellungen.': 'All fit parameters (B_res and ΔH in T and mT, α, amplitude/phase, complex amplitude, offsets, quality measures, status) + Kittel/LLG + settings.',
    'Alle Fits': 'All fits',
    'Alle Korridore nacheinander fitten.': 'Fit all corridors one after another.',
    'Alle Moden': 'All modes',
    'Alle Trennlinien von M{0} gelöscht.': 'All separators of M{0} deleted.',
    'Alle Verarbeitungen abschalten und die Rohdaten |S21| zeigen.': 'Switch off all processing and show the raw data |S21|.',
    'Alle gewählten Bestandteile werden mit gemeinsamem Basisnamen in den Zielordner geschrieben. Zoom, Fensterlayout und Achsengrößen werden nie gespeichert.': 'All selected parts are written to the target folder with a common base name. Zoom, window layout and axis sizes are never saved.',
    'Alle wieder aufnehmen': 'Re-include all',
    'Alles aus (Rohdaten |S21|)': 'All off (raw data |S21|)',
    'Alles speichern': 'Save everything',
    'Alles speichern nach {0} …': 'Save everything to {0} …',
    'Alles speichern …': 'Save everything …',
    'Alles speichern: {0} …': 'Save everything: {0} …',
    'Als Standard gespeichert (wird beim Start geladen): {0}': 'Saved as default (loaded at start): {0}',
    'Als Standard speichern (beim Start laden)': 'Save as default (load at start)',
    'Amplitude, Phase, komplexe Amplitude': 'Amplitude, phase, complex amplitude',
    "An (Standard): Grenzen ziehen, Bereichs-/Korridor-Fit und\n'Nochmal fitten' gelten als vom Nutzer geprüft → grüner Punkt mit\nblauem Rand, gehen in Kittel/LLG ein. Das Kriterienergebnis bleibt\neinsehbar (Export: problematisch_auto). Aus: Kriterien entscheiden\nauch nach manuellen Fits (gelb, wenn verletzt).": "On (default): dragging limits, region/corridor fit and\n'Refit' count as checked by the user → green point with\nblue edge, included in Kittel/LLG. The criteria result stays\nvisible (export: problematisch_auto). Off: the criteria decide\nalso after manual fits (yellow if violated).",
    'Angezeigte Mode – wie die Auswahl in der Korridorliste.': 'Displayed mode – same as the selection in the corridor list.',
    'Anker M{0} aus Grenzen': 'Anchor M{0} from limits',
    'Anker M{0} bei {1:.3f} GHz: {2:.4f} – {3:.4f} T.': 'Anchor M{0} at {1:.3f} GHz: {2:.4f} – {3:.4f} T.',
    'Anker M{0} entfernt': 'Anchor M{0} removed',
    'Anker M{0} gesetzt': 'Anchor M{0} set',
    'Anker M{0} verschoben': 'Anchor M{0} moved',
    'Anker setzen': 'Set anchor',
    'Anker setzen: zuerst einen Korridor anlegen.': 'Set anchor: create a corridor first.',
    'Anker: Grenzen würden sich kreuzen – nicht übernommen.': 'Anchor: limits would cross – not applied.',
    'Anpassung: Optimierer nicht konvergiert': 'Fit: optimizer did not converge',
    'Anpassung: normiertes Residuum > 0.35': 'Fit: normalized residual > 0.35',
    'Anpassung: reduziertes Chi² extrem': 'Fit: reduced chi² extreme',
    'Anzahl der Dips je Frequenz automatisch (BIC)': 'Number of dips per frequency automatic (BIC)',
    'Anzahl je Frequenz automatisch (BIC)': 'Number per frequency automatic (BIC)',
    'Ausgeblendete Punkte grau (hohl) anzeigen – auswählbar zum Wiederaufnehmen.': 'Show hidden points in gray (hollow) – selectable for re-including.',
    'Ausgewählte Punkte wieder in die Auswertung aufnehmen.': 'Re-include the selected points in the evaluation.',
    'Ausreißer (ignoriert)': 'Outliers (ignored)',
    'Ausreißer markieren': 'Mark outliers',
    'Ausreißer markieren aktiv: Punkt anklicken oder Kasten aufziehen (Klick auf einen grauen Punkt nimmt ihn wieder auf). Esc beendet.': 'Mark outliers active: click a point or drag a box (clicking a gray point re-includes it). Esc ends.',
    'Ausreißer markieren: Strg+M, dann Punkte im Farbplot anklicken oder per\nKasten markieren (Klick auf einen grauen Punkt nimmt ihn wieder auf).\nIgnorierte Punkte fehlen in Darstellung und Kittel/LLG-Fit. Im Kittel-\nFenster in einer Mode-Ansicht entfernte Punkte fehlen nur dort.': 'Mark outliers: Ctrl+M, then click points in the color plot or mark them\nwith a box (clicking a gray point re-includes it).\nIgnored points are missing from the display and the Kittel/LLG fit. Points\nremoved in a mode view of the Kittel window are missing only there.',
    'Ausreißer markiert ({0} Punkt(e))': 'Outliers marked ({0} point(s))',
    'Ausreißer wieder aufgenommen ({0})': 'Outliers re-included ({0})',
    'Ausschlusszone [{0:.3f}–{1:.3f} T, {2:.2f}–{3:.2f} GHz] aktiv: {4} Linescans neu gefittet.': 'Exclusion zone [{0:.3f}–{1:.3f} T, {2:.2f}–{3:.2f} GHz] active: {4} linescans refitted.',
    'Ausschlusszone anwenden …': 'Applying exclusion zone …',
    'Ausschlusszone einzeichnen': 'Draw exclusion zone',
    'Ausschlusszone entfernen …': 'Removing exclusion zone …',
    'Ausschlusszone entfernt': 'Exclusion zone removed',
    'Ausschlusszone entfernt: {0} Linescans neu gefittet.': 'Exclusion zone removed: {0} linescans refitted.',
    'Ausschlusszone hinzugefügt': 'Exclusion zone added',
    'Ausschlusszone: Rechteck um die auszuschließenden Punkte aufziehen (Esc bricht ab).': 'Exclusion zone: drag a rectangle around the points to exclude (Esc cancels).',
    'Ausschlusszonen': 'Exclusion zones',
    'Auswahl': 'Selection',
    'Auswahl aufheben': 'Clear selection',
    'Auswahl ausblenden': 'Hide selection',
    'Auswahl einblenden': 'Show selection',
    'Auswahl leeren (Esc).': 'Clear the selection (Esc).',
    'Auswahlwerkzeug: Punkt anklicken (an/aus) oder Kasten aufziehen.\nAktiv, solange Verschieben/Zoom aus sind.': 'Selection tool: click a point (on/off) or drag a box.\nActive while pan/zoom are off.',
    'Auswertung exportieren': 'Export evaluation',
    'Auswertung starten': 'Start evaluation',
    'Auswertung von <b>{0}</b> Linescans ({1:.2f}-{2:.2f} GHz, {3:.3f}-{4:.3f} T). Unterabtastung beschleunigt; Bereiche grenzen die Auswertung ein. <b>Tipp:</b> Ein enger Feldbereich und „jeder n-te Feldpunkt“ machen den Auto-Fit deutlich schneller – bei mehreren Resonanzen besonders.': 'Evaluation of <b>{0}</b> linescans ({1:.2f}-{2:.2f} GHz, {3:.3f}-{4:.3f} T). Subsampling speeds things up; ranges restrict the evaluation. <b>Tip:</b> a narrow field range and “every n-th field point” make the auto-fit much faster – especially with several resonances.',
    'Auswertungsauswahl: ': 'Evaluation selection: ',
    'Auswählen': 'Select',
    'Auswählen: Punkt anklicken (an/aus) oder Kasten aufziehen → „Auswahl ausblenden“ (Entf)': 'Select: click a point (on/off) or drag a box → “Hide selection” (Del)',
    'Auszuwertender Bereich': 'Range to evaluate',
    'Auto-Fit (alle)': 'Auto-fit (all)',
    'Auto-Fit abgebrochen: {0} von {1} Frequenzen gefittet, {2} problematisch – der Rest bleibt „nicht gefittet“ (Korridor/Bereich fitten den Rest bei Bedarf).': 'Auto-fit cancelled: {0} of {1} frequencies fitted, {2} problematic – the rest stays “not fitted” (corridor/region fit the rest if needed).',
    'Auto-Fit fertig: {0} Fits, {1} problematisch.': 'Auto-fit finished: {0} fits, {1} problematic.',
    'Auto-Fit läuft …': 'Auto-fit running …',
    'Auto-Fit {0}. {1} Fits, {2} problematisch.': 'Auto-fit {0}. {1} fits, {2} problematic.',
    'Auto-Fit: Bereich & Jumper': 'Auto-fit: range & jumper',
    'Auto-Fit: Mode 1 hat einen Korridor – gefittet wird nur darin (keine Fenstersuche).': 'Auto-fit: mode 1 has a corridor – fitting happens only inside it (no window search).',
    'Auto-Fit: anschließend werden die Korridore ': 'Auto-fit: afterwards the corridors ',
    'Auto-Sicherung': 'Auto-backup',
    'Auto-Sicherung fehlgeschlagen: {0}': 'Auto-backup failed: {0}',
    'Auto-Sicherung geschrieben ({0}).': 'Auto-backup written ({0}).',
    'Auto-Sicherung wiederherstellen …': 'Restore auto-backup …',
    'Automatische Fensterbreite = Faktor × lokale Halbwertsbreite\nder Resonanz. Größer = mehr Untergrund im Fit, kleiner = enger.': 'Automatic window width = factor × local half width\nof the resonance. Larger = more background in the fit, smaller = narrower.',
    'B max (T)': 'B max (T)',
    'B min (T)': 'B min (T)',
    'B_res am Fensterrand': 'B_res at window edge',
    'B_res ausserhalb Fenster': 'B_res outside window',
    'B_res-Unsicherheit zu gross': 'B_res uncertainty too large',
    'Basisname:': 'Base name:',
    'Be&wertung des aktuellen Fits': '&Rating of the current fit',
    'Bedienung & Infos': 'Usage & info',
    'Bedienung & Infos …': 'Usage & info …',
    'Beenden': 'Quit',
    'Beim Blättern (Pfeiltasten, Zurück/Weiter) nur gefittete Frequenzen der\nangezeigten Mode anspringen – z. B. nach einem Auto-Fit mit Jumper.': 'When browsing (arrow keys, Back/Next) only jump to fitted frequencies of the\ndisplayed mode – e.g. after an auto-fit with jumper.',
    'Bereich = sichtbarer Farbplot-Ausschnitt (Zoom).': 'Range = visible color plot region (zoom).',
    'Bereich neu fitten': 'Refit region',
    'Bereich neu fitten: Rechteck um die Mode aufziehen (Esc bricht ab).': 'Refit region: drag a rectangle around the mode (Esc cancels).',
    'Bereichs-Fit': 'Region fit',
    "Bereichs-Fit [{0:.3f}–{1:.3f} T, {2:.2f}–{3:.2f} GHz{4}]: {5} gefittet, {6} problematisch, {7} übersprungen (ohne Daten/Modus 'ergänzen').": "Region fit [{0:.3f}–{1:.3f} T, {2:.2f}–{3:.2f} GHz{4}]: {5} fitted, {6} problematic, {7} skipped (no data/mode 'complete').",
    'Bereichs-Fit abgebrochen.': 'Region fit cancelled.',
    'Bereichs-Fit {0:.1f}–{1:.1f} GHz …': 'Region fit {0:.1f}–{1:.1f} GHz …',
    'Bereit.': 'Ready.',
    'Bereit. Bitte eine TDMS-Datei laden (Strg+O).': 'Ready. Please load a TDMS file (Ctrl+O).',
    'Beschnittene Linescans und Fitkurven im TDMS-Format.': 'Cropped linescans and fit curves in TDMS format.',
    'Bewertung dieses Fits setzen: gut bestätigen (Strg+1), problematisch (Strg+2),\nautomatisch nach Kriterien (Strg+3), ignorieren/wieder aufnehmen (Strg+I).': 'Set the rating of this fit: confirm good (Ctrl+1), problematic (Ctrl+2),\nautomatic by criteria (Ctrl+3), ignore/re-include (Ctrl+I).',
    'Bewertung f={0:.2f} GHz: {1} (Kriterien: {2}).': 'Rating f={0:.2f} GHz: {1} (criteria: {2}).',
    'Bewertung „{0}“ (f={1:.2f} GHz)': 'Rating “{0}” (f={1:.2f} GHz)',
    'Bewertung: diese Frequenz ist noch nicht gefittet.': 'Rating: this frequency is not fitted yet.',
    'Bitte einen Basisnamen angeben.': 'Please enter a base name.',
    'Bitte mindestens einen Bestandteil wählen.': 'Please select at least one part.',
    'Bitte zuerst eine TDMS-Datei laden.': 'Please load a TDMS file first.',
    'Bitte zuerst fitten (Auto-Fit, Korridor oder Bereich).': 'Please fit first (auto-fit, corridor or region).',
    'Bitte zuerst fitten – gespeichert wird der komplette Auswertungszustand.': 'Please fit first – the complete evaluation state is saved.',
    "Blatt 'Einzelfits' (Spalten nach Export-Spalten-Einstellung),\n'Global' (Kittel/LLG in T und mT) und Zusatzblätter.": "Sheet 'Einzelfits' (columns per export column setting),\n'Global' (Kittel/LLG in T and mT) and additional sheets.",
    'CSV (*.csv)': 'CSV (*.csv)',
    'CSV gespeichert: {0}': 'CSV saved: {0}',
    "CSV im deutschen Format (';' und Dezimalkomma)": "CSV in German format (';' and decimal comma)",
    'CSV speichern': 'Save CSV',
    'Call-Trace (Debug)': 'Call trace (debug)',
    'Chi2 extrem': 'chi² extreme',
    'Cividis (farbfehlsichtigkeitsfreundlich)': 'Cividis (color-vision-deficiency friendly)',
    'Darstellung': 'Display',
    'Datei → „TDMS laden …“ (Strg+O) öffnet eine Messung.\nDanach lässt sich die Karte allein zur Datenansicht nutzen\n(Verarbeitung: derivative divide, divide slice, …).': 'File → “Load TDMS …” (Ctrl+O) opens a measurement.\nThe map can then be used for viewing data only\n(processing: derivative divide, divide slice, …).',
    "Der Datensatz hat keine Kanal-Zuordnung. Bitte die TDMS-Datei über 'TDMS laden' öffnen und die Kanäle den Rollen zuordnen.": "The data set has no channel assignment. Please open the TDMS file via 'Load TDMS' and assign the channels to the roles.",
    'Die TDMS-Quelle {0!r} wurde nicht gefunden. Bitte die Messdatei auswählen.': 'The TDMS source {0!r} was not found. Please select the measurement file.',
    'Die angezeigte Matrix (nach Verarbeitungskette und Darstellung):\nZeilen = Frequenzen, Spalten = Feldwerte.': 'The displayed matrix (after processing chain and display):\nrows = frequencies, columns = field values.',
    'Diese Frequenz (gewählte Mode) mit dem aktuellen Fenster bzw. Korridor\nneu fitten.': 'Refit this frequency (selected mode) with the current window or\ncorridor.',
    'Dieselben Spalten wie Excel als Textdatei.': 'The same columns as Excel, as a text file.',
    "Direkt in deutschem Excel/LibreOffice lesbar; sonst ',' und Punkt.": "Directly readable in German Excel/LibreOffice; otherwise ',' and point.",
    'Dispersion (Kittel, {0}){1}': 'Dispersion (Kittel, {0}){1}',
    'Eigenes Auswertungsfenster: Kittel- und LLG-Fit mit Feld auf der x-Achse, Punkte direkt im Plot entfernen, Export mit Fehlermaßen (T und mT).': 'Separate evaluation window: Kittel and LLG fit with the field on the x axis, remove points directly in the plot, export with error measures (T and mT).',
    'Ein Hintergrundprozess läuft noch. Trotzdem beenden?': 'A background process is still running. Quit anyway?',
    'Eine Auto-Sicherung des letzten Arbeitsstands ist vorhanden (Datei → Auto-Sicherung wiederherstellen).': 'An auto-backup of the last working state exists (File → Restore auto-backup).',
    'Einstellungen angewendet.': 'Settings applied.',
    'Einstellungen auf Programm-Standard zurückgesetzt (Datei bleibt, bis „Als Standard speichern“ erneut ausgeführt wird).': 'Settings reset to program defaults (the file stays until “Save as default” is run again).',
    'Einstellungen geladen: {0}': 'Settings loaded: {0}',
    'Einstellungen gespeichert: {0}': 'Settings saved: {0}',
    'Einstellungen laden': 'Load settings',
    'Einstellungen laden …': 'Load settings …',
    'Einstellungen speichern': 'Save settings',
    'Einstellungen speichern unter …': 'Save settings as …',
    'Einzelfits': 'Single fits',
    'Einzelfits als CSV (Listendaten)': 'Single fits as CSV (list data)',
    'Einzelfits als CSV (Listendaten) …': 'Single fits as CSV (list data) …',
    'Einzelfits als Excel (.xlsx) – alle Parameter, Kittel/LLG, Einstellungen': 'Single fits as Excel (.xlsx) – all parameters, Kittel/LLG, settings',
    'Einzelfits als Excel …': 'Single fits as Excel …',
    'Entfernen': 'Remove',
    'Entlang welcher Achse gerechnet wird: Feldachse (Standard, wie im Paper)\noder Frequenzachse.': 'Axis along which the calculation runs: field axis (default, as in the paper)\nor frequency axis.',
    'Entwickler-Werkzeug: zeigt live, welche polderfit-Funktionen aufgerufen werden. Nur zur Fehlersuche einschalten.': 'Developer tool: shows live which polderfit functions are called. Switch on for debugging only.',
    'Ergebnisse verwerfen (rückgängig mit Strg+Z): alle Fits oder nur die der angezeigten Mode. Korridore, Zonen und Einstellungen bleiben.': 'Discard results (undo with Ctrl+Z): all fits or only those of the displayed mode. Corridors, zones and settings are kept.',
    'Erst „Resonanzen im Korridor“ auf 2 oder mehr stellen.': 'First set “Resonances in corridor” to 2 or more.',
    'Erwartete Zahl nahe beieinander liegender Resonanzen (Dips) im gefundenen\nFenster jeder Frequenz. 1 = klassisch. Bei > 1 werden alle Dips wie im\nKorridor per Summenfit mit Segment-Schranken gefittet (Mode 1 = erster Dip).\nMit vorhandenen Korridoren bestimmen die Korridore die Moden.': 'Expected number of closely spaced resonances (dips) in the found\nwindow of each frequency. 1 = classic. For > 1 all dips are fitted as in the\ncorridor by a sum fit with segment bounds (mode 1 = first dip).\nWith existing corridors, the corridors determine the modes.',
    'Es läuft bereits ein Hintergrundprozess – bitte warten.': 'A background process is already running – please wait.',
    'Es läuft ein Hintergrundprozess – Modus nicht gestartet.': 'A background process is running – mode not started.',
    'Excel (*.xlsx)': 'Excel (*.xlsx)',
    'Excel (Parameter mit 1σ-Fehlern in T und mT, alle Punkte; bei mehreren\nModen zusätzlich je Mode ein Blatt), CSV der Punkte (Listendaten) und\nPlot als PNG + PDF.': 'Excel (parameters with 1σ errors in T and mT, all points; with several\nmodes one extra sheet per mode), CSV of the points (list data) and\nplot as PNG + PDF.',
    'Excel gespeichert: {0}': 'Excel saved: {0}',
    'Excel speichern': 'Save Excel',
    'Export': 'Export',
    'Export-Spalten (Excel/CSV)': 'Export columns (Excel/CSV)',
    'Export-Spalten (Standard) …': 'Export columns (default) …',
    'Export-Spalten: ': 'Export columns: ',
    'Exportieren … (Excel + CSV + Plot)': 'Export … (Excel + CSV + plot)',
    'Externes Feld nach Sweep (T)': 'External field after sweep (T)',
    'Externes Feld vor Sweep (T)': 'External field before sweep (T)',
    'FEHLER beim Inspizieren: {0}': 'ERROR while inspecting: {0}',
    'FEHLER beim Speichern ({0}): {1}': 'ERROR while saving ({0}): {1}',
    'FEHLER: ': 'ERROR: ',
    'Farbplot als Bild': 'Color plot as image',
    'Farbplot als Bild (PNG + PDF, mit Overlays)': 'Color plot as image (PNG + PDF, with overlays)',
    'Farbplot als Bild …': 'Color plot as image …',
    'Farbplot gespeichert: {0}': 'Color plot saved: {0}',
    'Farbplot, Zoom und Panels auf den Auslieferungszustand bringen – ohne Daten oder Fits zu verlieren.': 'Reset color plot, zoom and panels to the delivery state – without losing data or fits.',
    'Farbplot-Matrix als CSV': 'Color plot matrix as CSV',
    'Farbplot-Matrix als CSV (verarbeitete Daten)': 'Color plot matrix as CSV (processed data)',
    'Farbplot-Matrix als CSV …': 'Color plot matrix as CSV …',
    'Farbplot-Matrix gespeichert: {0} ({1} · {2})': 'Color plot matrix saved: {0} ({1} · {2})',
    "Farbskala des Falschfarbenbilds. 'Grau' hält den Hintergrund neutral,\ndamit die Signalfarben der Fit-Punkte (grün/gelb/rot/blau) hervorstechen;\nViridis/Cividis sind wahrnehmungsgleich (auch für Farbfehlsichtige).": "Color scale of the false-color image. 'Gray' keeps the background neutral\nso the signal colors of the fit points (green/yellow/red/blue) stand out;\nViridis/Cividis are perceptually uniform (also for color vision deficiency).",
    'Farbskala des Farbplots': 'Color scale of the color plot',
    'Farbskala:': 'Color scale:',
    'Fehlende Pflichtrollen: ': 'Missing required roles: ',
    'Fehler': 'Error',
    'Feld $\\mu_0 H$ (T)': 'Field $\\mu_0 H$ (T)',
    'Feld bis:': 'Field to:',
    'Feld von:': 'Field from:',
    'Feld- bzw. Frequenzwert des gewählten Referenz-Index.': 'Field or frequency value of the selected reference index.',
    'Feldachse': 'field axis',
    'Feldachse - jeder n-te Punkt:': 'Field axis - every n-th point:',
    'Fenster mitteln (zusätzliche Glättung)': 'Average windows (additional smoothing)',
    'Fenster umfasst {0:.0%} des Feldsweeps – Linienbreite wird überschätzt. Grenzen enger an die Resonanz ziehen.': 'Window covers {0:.0%} of the field sweep – linewidth is overestimated. Drag the limits closer to the resonance.',
    'Fenster: B_res am Rand des Fitfensters': 'Window: B_res at the edge of the fit window',
    'Fenster: B_res außerhalb des Fitfensters': 'Window: B_res outside the fit window',
    'Fenster: weniger als 12 Messpunkte': 'Window: fewer than 12 data points',
    'Fenster: µ₀ΔH unter 1.5 Feldschritten': 'Window: µ₀ΔH below 1.5 field steps',
    'Fensterbreite fest:': 'Fixed window width:',
    'Fensterbreite-Faktor:': 'Window width factor:',
    'Fensterlayout zurückgesetzt.': 'Window layout reset.',
    'Fensterlayout zurücksetzen': 'Reset window layout',
    'Fenstersuche': 'Window search',
    'Fit Im': 'Fit Im',
    'Fit Re': 'Fit Re',
    'Fit fehlgeschlagen': 'Fit failed',
    'Fit-Ergebnisse gelöscht': 'Fit results deleted',
    'Fit-Ergebnisse löschen': 'Delete fit results',
    'Fit-Ergebnisse löschen …': 'Delete fit results …',
    'Fit-Werkzeuge ein-/ausblenden: Korridore je Mode (nur im Korridor fitten) und Ausschlusszonen (Messpunkte aus allen Fits ausnehmen).': 'Show/hide fit tools: corridors per mode (fit only inside the corridor) and exclusion zones (exclude data points from all fits).',
    'Fitfenster': 'Fit window',
    'Fitkurven als TDMS': 'Fit curves as TDMS',
    'Fitkurven als TDMS …': 'Fit curves as TDMS …',
    'Fits': 'Fits',
    'Fits wiederherstellen': 'Restoring fits',
    'Frequenz (GHz)': 'Frequency (GHz)',
    'Frequenz (Hz)': 'Frequency (Hz)',
    'Frequenz bis:': 'Frequency to:',
    'Frequenz von:': 'Frequency from:',
    'Frequenz-Ausschluesse (GHz):': 'Frequency exclusions (GHz):',
    'Frequenzachse': 'frequency axis',
    'Frequenzachse - jeder n-te Linescan:': 'Frequency axis - every n-th linescan:',
    "Frequenzbaender (GHz), die NICHT ausgewertet werden - mehrere mit ';' trennen.": "Frequency bands (GHz) that are NOT evaluated - separate several with ';'.",
    'Fun&ktionen': 'F&unctions',
    'Ganzen Feldsweep zeigen statt aufs Resonanzband zu zoomen.': 'Show the whole field sweep instead of zooming to the resonance band.',
    'Ganzer Bereich': 'Full range',
    'Geladen: {0} ({1}, {2} Frequenzen). Daten ansehen (Verarbeitung), Korridor/Bereich fitten oder Auto-Fit starten.': 'Loaded: {0} ({1}, {2} frequencies). View data (processing), fit corridor/region or start auto-fit.',
    'Geladen: {0} – {1}, {2} Frequenzen (Profil: {3}).': 'Loaded: {0} – {1}, {2} frequencies (profile: {3}).',
    "Gemeinsamer Dateiname ohne Endung, z. B. 'CoFe_5K_oop'.": "Common file name without extension, e.g. 'CoFe_5K_oop'.",
    'Genau eine Verarbeitung ist aktiv; Erklärung je Option per Tooltip.': 'Exactly one processing step is active; each option is explained in its tooltip.',
    'Gesamtansicht (alle Punkte)': 'Full view (all points)',
    'Gespeichert:\n': 'Saved:\n',
    'Gespeicherte Sitzung fortsetzen: TDMS wird neu gelesen, die Fits werden mit den gespeicherten Fenstern deterministisch wiederhergestellt.': 'Continue a saved session: the TDMS is read again, the fits are restored deterministically with the saved windows.',
    'Gewählte (sonst zuletzt gezeichnete) Zone entfernen.': 'Remove the selected (otherwise the last drawn) zone.',
    'Gewählte Mode an allen Frequenzen im Korridor fitten (Einzelfit je\nFrequenz, nur Punkte im Korridor). Dialog: Frequenzbereich, Modus, Jumper.': 'Fit the selected mode at all frequencies in the corridor (single fit per\nfrequency, only points inside the corridor). Dialog: frequency range, mode, jumper.',
    'Gewählte Punkte aus der Kittel-/LLG-Auswertung ausschließen (Entf) –\nwird ins Hauptfenster/den Farbplot übernommen (grau); rückgängig: Strg+Z.': 'Exclude the selected points from the Kittel/LLG evaluation (Del) –\napplied to the main window/color plot (gray); undo: Ctrl+Z.',
    'Gewählte Zeile = Mode im Linescan-Panel.': 'Selected row = mode in the linescan panel.',
    'Gewählte Zeile entfernen: Korridor samt Fits seiner Moden, bei Auto-Fit-Moden\n(ohne Korridor) nur die Fits dieser Mode. Rückgängig mit Strg+Z.': 'Remove the selected row: corridor including the fits of its modes; for auto-fit modes\n(without corridor) only the fits of this mode. Undo with Ctrl+Z.',
    'Gewählte ausgeblendete (graue) Punkte wieder in die Auswertung aufnehmen.': 'Re-include the selected hidden (gray) points in the evaluation.',
    'Grau (neutral – Signalfarben der Fits stechen hervor)': 'Gray (neutral – signal colors of the fits stand out)',
    "Grenze des Kriteriums 'alpha unphysikalisch' (gelbe Warnung).\n0 = automatisch (halbe α-Obergrenze). Bei Proben mit real breiten\nLinien (nanostrukturiertes CoFe, FeCr2S4) anheben, damit gute Fits\nnicht dauernd als problematisch gelten; bei schwach gedämpften\nProben bis 0.00001 absenkbar.": "Limit of the criterion 'alpha unphysical' (yellow warning).\n0 = automatic (half the α upper limit). Raise it for samples with really broad\nlines (nanostructured CoFe, FeCr2S4) so that good fits are not\nconstantly treated as problematic; can be lowered to 0.00001 for weakly\ndamped samples.",
    'Grenzen gezogen (f={0:.2f} GHz)': 'Limits dragged (f={0:.2f} GHz)',
    'Größe:': 'Quantity:',
    'Gründe: ': 'Reasons: ',
    'Gütemaße (R², Residuum, χ²)': 'Quality measures (R², residual, χ²)',
    'Halbe Korridorbreite (eng halten): gilt für den gewählten Korridor – Ändern\nsetzt alle seine Anker sofort auf Mitte ± Wert – und für neu angelegte.': 'Half corridor width (keep it narrow): applies to the selected corridor – changing it\nimmediately sets all its anchors to center ± value – and to newly created ones.',
    "Harte obere Schranke der Gilbert-Dämpfung α im Einzelfit.\nStandard 0.1 (Metalle/Granate). Für sehr breite Resonanzen\n(z. B. FeCr2S4 mit α ≈ 0.2–0.5) anheben – sonst klemmt der Fit\nan der Schranke ('alpha an Grenze'). Für sehr schwach gedämpfte\nProben bis 0.00001 absenkbar (Pfeile/Mausrad: dekadische Schritte).": "Hard upper bound of the Gilbert damping α in the single fit.\nDefault 0.1 (metals/garnets). Raise it for very broad resonances\n(e.g. FeCr2S4 with α ≈ 0.2–0.5) – otherwise the fit sticks\nto the bound ('alpha at limit'). Can be lowered to 0.00001 for very weakly\ndamped samples (arrows/mouse wheel: decadic steps).",
    'Hineinzoomen: Rechteck aufziehen': 'Zoom in: drag a rectangle',
    'Hinweis': 'Note',
    'Hinweis: bestehende Einzelfits bleiben unverändert – neue Parameter wirken ab dem nächsten (Auto-/Nach-)Fit; die Kittel/LLG-Auswertung rechnet sofort neu.': 'Note: existing single fits stay unchanged – new parameters apply from the next (auto/re)fit; the Kittel/LLG evaluation recalculates immediately.',
    'Hinweis: viele Problemfits – bei mehreren Moden (z. B. vermiedene Kreuzung) je Mode einen Korridor anlegen und „Korridor fitten …“ verwenden; die Fenstersuche kann dort zwischen den Ästen springen.': 'Note: many problem fits – with several modes (e.g. avoided crossing) create one corridor per mode and use “Fit corridor …”; the window search can jump between the branches there.',
    'Hinweis: {0} Fits mit „B_res am Fensterrand“ – der Korridor ist zu eng oder liegt neben der Resonanz (bei mehreren Dips müssen ALLE Dips im Korridor liegen): Breite „± mT“ erhöhen oder Anker nachsetzen und erneut fitten.': 'Note: {0} fits with “B_res at window edge” – the corridor is too narrow or lies next to the resonance (with several dips ALL dips must lie inside the corridor): increase the width “± mT” or add anchors and fit again.',
    'Ignoriert (Ausreißer): {0} Punkt(e) ({1}{2} GHz) – insgesamt {3} ausgeschlossen.': 'Ignored (outliers): {0} point(s) ({1}{2} GHz) – {3} excluded in total.',
    'Ignorierte Punkte (Ausreißer) grau anzeigen': 'Show ignored points (outliers) in gray',
    'Im Linescan-Panel den ganzen Feldsweep zeigen statt aufs Resonanzband zu zoomen.': 'Show the whole field sweep in the linescan panel instead of zooming to the resonance band.',
    'Im Linescan-Panel zwischen zwei Dips klicken → gelbe Trennlinie (harte\nGrenze). Sie wandert entlang der Mode mit (relativ zur Korridormitte) und\ngilt für alle Fits dieses Korridors; an anderen Frequenzen nachsetzen oder\nziehen, wenn sie abweicht. Esc oder erneuter Klick auf den Knopf beendet.': 'Click between two dips in the linescan panel → yellow separator (hard\nlimit). It moves along the mode (relative to the corridor center) and\napplies to all fits of this corridor; add or drag it at other frequencies\nif it deviates. Esc or clicking the button again ends.',
    'Im S21': 'Im S21',
    'Im S21 (Messung)': 'Im S21 (measured)',
    'Im(S21)': 'Im(S21)',
    'Import verworfen – Zuordnung erneut bearbeiten.': 'Import discarded – edit the assignment again.',
    'Import-Vorschau': 'Import preview',
    'Index außerhalb der Achse': 'Index outside the axis',
    'Index:': 'Index:',
    'JSON (*.json)': 'JSON (*.json)',
    'Je Frequenz werden 1 … n Linien gefittet und das sparsamste Modell gewählt,\ndas die Daten erklärt. Wo weniger Dips sind, entfällt die überzählige Linie.\nNur Summenfit; manuelle Trennlinien haben Vorrang. Rechenzeit etwa 2–3-fach.': 'At each frequency 1 … n lines are fitted and the most economical model\nthat explains the data is chosen. Where there are fewer dips, the extra line is dropped.\nSum fit only; manual separators take precedence. Computing time about 2–3 times.',
    'Je Mode ein Korridor entlang der Resonanz. Jede Mode wird NUR auf den\nMesspunkten ihres Korridors gefittet (Einzelfit, kein Summenfit).\nOhne Korridor gilt für Mode 1 das AutoWindow-Fenster des Auto-Fits.\nDie gewählte Zeile ist die Mode im Linescan-Panel.': 'One corridor per mode along the resonance. Each mode is fitted ONLY on the\ndata points of its corridor (single fit, no sum fit).\nWithout a corridor, mode 1 uses the AutoWindow window of the auto-fit.\nThe selected row is the mode in the linescan panel.',
    'Jumper:': 'Jumper:',
    'Jumper: nur jede n-te Frequenz des Bereichs fitten (schneller;\n1 = alle Frequenzen).': 'Jumper: fit only every n-th frequency of the range (faster;\n1 = all frequencies).',
    'Keine Ausreißer markiert.': 'No outliers marked.',
    'Keine Auto-Sicherung vorhanden ({0}).': 'No auto-backup available ({0}).',
    'Keine Messung geladen': 'No measurement loaded',
    'Keine problematischen Fits mehr.': 'No problematic fits left.',
    'Kittel M{0}': 'Kittel M{0}',
    'Kittel-/LLG-Fits: ungewichtet (Standard, alle Punkte gleich – wie\ndas LabVIEW-FTF) oder optional gewichtet mit den 1σ-Unsicherheiten\nder Einzelfits (w = 1/u², ABW Abschn. 6.3; betont die präzisesten\nPunkte, wenige Punkte können dominieren).\nWeichen beide Ergebnisse stark voneinander ab, tragen Modell-\nabweichungen (nicht Rauschen) die Streuung.': 'Kittel/LLG fits: unweighted (default, all points equal – like\nthe LabVIEW FTF) or optionally weighted with the 1σ uncertainties\nof the single fits (w = 1/u², ABW sec. 6.3; emphasizes the most precise\npoints, a few points can dominate).\nIf both results differ strongly, model deviations\n(not noise) cause the scatter.',
    'Kittel-/LLG-Gewichtung:': 'Kittel/LLG weighting:',
    'Kittel-Fit': 'Kittel fit',
    'Kittel-Geometrie:': 'Kittel geometry:',
    'Kittel-Geometrie: {0} (gilt auch für den Export).': 'Kittel geometry: {0} (also applies to the export).',
    'Kittel-oop-Fit mit festem γ (aus dem g-Faktor oben): nur µ₀M_eff frei.': 'Kittel oop fit with fixed γ (from the g-factor above): only µ₀M_eff free.',
    'Kittel/LLG exportiert: ': 'Kittel/LLG exported: ',
    'Kittel/LLG-Auswertung': 'Kittel/LLG evaluation',
    'Kittel/LLG-Auswertung (Excel + CSV + Plot PNG/PDF)': 'Kittel/LLG evaluation (Excel + CSV + plot PNG/PDF)',
    'Kittel/LLG-Auswertung exportieren': 'Export Kittel/LLG evaluation',
    'Kittel/LLG-Auswertung exportieren …': 'Export Kittel/LLG evaluation …',
    'Kittel/LLG-Auswertung …': 'Kittel/LLG evaluation …',
    'Kittel/LLG: {0} Ausreißer ausgeschlossen ({1} Punkte verbleiben).': 'Kittel/LLG: {0} outliers excluded ({1} points remain).',
    'Klick = Trennlinie setzen · gelbe Linien ziehen': 'Click = set separator · drag yellow lines',
    'Konvention: Felder als µ₀H in Tesla, γ = g·µ_B/ħ in rad/(s·T) (Müller 2023, Kap. 2). Änderungen wirken ab dem nächsten (Auto-/Nach-)Fit; die Kittel/LLG-Auswertung rechnet sofort neu. Speichern/Laden als Voreinstellung: Menü Datei → Einstellungen.': 'Convention: fields as µ₀H in tesla, γ = g·µ_B/ħ in rad/(s·T) (Müller 2023, ch. 2). Changes apply from the next (auto/re)fit; the Kittel/LLG evaluation recalculates immediately. Save/load as preset: menu File → Settings.',
    'Korridor M{0}': 'Corridor M{0}',
    'Korridor M{0} angelegt': 'Corridor M{0} created',
    'Korridor M{0} angelegt: ±{1:.0f} mT um ({2:.3f} T, {3:.2f} GHz) – ({4:.3f} T, {5:.2f} GHz). Anker setzen/ziehen zum Nachführen; dann „Korridor fitten …“.': 'Corridor M{0} created: ±{1:.0f} mT around ({2:.3f} T, {3:.2f} GHz) – ({4:.3f} T, {5:.2f} GHz). Set/drag anchors to follow the mode; then “Fit corridor …”.',
    'Korridor M{0} entfernt': 'Corridor M{0} removed',
    'Korridor M{0} entfernt (samt Fits dieser Mode).': 'Corridor M{0} removed (including the fits of this mode).',
    'Korridor M{0}: Verfahren „{1}“': 'Corridor M{0}: method “{1}”',
    'Korridor M{0}: {1} Fits, {2} problematisch.': 'Corridor M{0}: {1} fits, {2} problematic.',
    'Korridor M{0}: {1} Resonanz(en)': 'Corridor M{0}: {1} resonance(s)',
    'Korridor M{0}: {1} Resonanz(en) vorgegeben': 'Corridor M{0}: {1} resonance(s) specified',
    'Korridor M{0}: ±{1:.0f} mT': 'Corridor M{0}: ±{1:.0f} mT',
    'Korridor anlegen': 'Create corridor',
    'Korridor bei dieser Frequenz leer.': 'Corridor empty at this frequency.',
    'Korridor fitten …': 'Fit corridor …',
    'Korridor {0} fitten': 'Fit corridor {0}',
    'Korridor {0}: je Frequenz ein Einzelfit nur auf den Messpunkten im Korridor ({1}).': 'Corridor {0}: one single fit per frequency, only on the data points inside the corridor ({1}).',
    'Korridor-Fit abgebrochen.': 'Corridor fit cancelled.',
    'Korridor-Fit {0}': 'Corridor fit {0}',
    'Korridor-Fit {0} ({1:.2f}–{2:.2f} GHz{3}): {4} gefittet, {5} problematisch, {6} übersprungen.': 'Corridor fit {0} ({1:.2f}–{2:.2f} GHz{3}): {4} fitted, {5} problematic, {6} skipped.',
    'Korridor-Fit {0} läuft …': 'Corridor fit {0} running …',
    'Korridor-Fit: bitte zuerst eine TDMS-Datei laden.': 'Corridor fit: please load a TDMS file first.',
    'Korridor-Fit: bitte zuerst einen Korridor anlegen.': 'Corridor fit: please create a corridor first.',
    'Korridor-Fit: der Korridor liegt an keiner Frequenz im Datenbereich.': 'Corridor fit: the corridor does not lie within the data range at any frequency.',
    'Korridor: {0}': 'Corridor: {0}',
    'Korridore': 'Corridors',
    'Korridore (Moden)': 'Corridors (modes)',
    'LLG M{0}': 'LLG M{0}',
    'LLG-Fit': 'LLG fit',
    'Lade Projekt {0} …': 'Loading project {0} …',
    'Lade {0} …': 'Loading {0} …',
    'Lade {0} … (große Dateien brauchen bis zu einer Minute)': 'Loading {0} … (large files take up to a minute)',
    'Laden abgebrochen (Zuordnung nicht bestätigt).': 'Loading cancelled (assignment not confirmed).',
    'Landé-g-Faktor. γ = g·µ_B/ħ wird daraus abgeleitet und überall\nverwendet: Einzelfits (ΔH = 2ωα/γ), Fenstersuche und als\nStartwert des Kittel-Fits.': 'Landé g-factor. γ = g·µ_B/ħ is derived from it and used everywhere:\nsingle fits (ΔH = 2ωα/γ), window search and as the\nstart value of the Kittel fit.',
    'Laufenden Auto-/Bereichs-/Korridor-Fit geordnet beenden; bisherige Ergebnisse bleiben erhalten.': 'End the running auto/region/corridor fit cleanly; results so far are kept.',
    'Laufenden Fit geordnet beenden – bisherige Ergebnisse bleiben erhalten.': 'End the running fit cleanly – results so far are kept.',
    'Layout nicht automatisch bestimmbar (Kanal-Laengen passen zu keinem bekannten Muster) – bitte explizit waehlen.': 'Layout cannot be determined automatically (channel lengths match no known pattern) – please choose it explicitly.',
    'Layout nicht automatisch bestimmbar – bitte explizit waehlen.': 'Layout cannot be determined automatically – please choose it explicitly.',
    'Layout-Vorschlag: {0}': 'Suggested layout: {0}',
    'Leeren': 'Clear',
    'Letzte Änderung zurücknehmen: Korridor/Anker, Ausschlusszone, Ausreißer, Bewertung oder Nachfit (Strg+Z).': 'Undo the last change: corridor/anchor, exclusion zone, outlier, rating or refit (Ctrl+Z).',
    'Letzten automatisch gesicherten Arbeitsstand laden (wird 15 s nach jeder Änderung und beim Beenden geschrieben).': 'Load the last automatically saved working state (written 15 s after every change and on exit).',
    'Linescan-Fit': 'Linescan fit',
    'Linescan-Fit-Panel ein-/ausblenden (abdockbar für den zweiten Monitor).': 'Show/hide the linescan fit panel (can be undocked for a second monitor).',
    'Linescan: ganzer Feldsweep': 'Linescan: whole field sweep',
    'Linie nicht aufgelöst': 'line not resolved',
    'Linienbreite $\\mu_0\\Delta H$ (mT)': 'Linewidth $\\mu_0\\Delta H$ (mT)',
    'Linienbreite (LLG){0}': 'Linewidth (LLG){0}',
    'Liste der ignorierten Punkte ein-/ausblenden.': 'Show/hide the list of ignored points.',
    'M1': 'M1',
    'Magma': 'Magma',
    'Manuelle Nachfits automatisch als „gut – bestätigt“ bewerten': 'Rate manual refits automatically as “good – confirmed”',
    'Messpunkte in einer Zone (Rechteck Feld × Frequenz) werden aus ALLEN\n(Nach-)Fits ausgenommen; betroffene Linescans rechnen sofort neu.': 'Data points in a zone (rectangle field × frequency) are excluded from ALL\n(re)fits; affected linescans are recalculated immediately.',
    'Mode 1 … n (je ein Korridor mit eigenem Kittel-/LLG-Fit) oder alle Moden.': 'Mode 1 … n (one corridor each with its own Kittel/LLG fit) or all modes.',
    'Mode {0}': 'Mode {0}',
    'Mode {0} (Korridor M{0})': 'Mode {0} (corridor M{0})',
    'Mode {0}: kein Korridor – bitte zuerst einen Korridor anlegen.': 'Mode {0}: no corridor – please create a corridor first.',
    'Mode:': 'Mode:',
    'Moden = vorhandene Korridore (werden mitgefittet).': 'Modes = existing corridors (fitted as well).',
    'Modus beendet.': 'Mode ended.',
    'Modus nicht verfügbar: bitte zuerst eine TDMS-Datei laden.': 'Mode not available: please load a TDMS file first.',
    'Modus nicht verfügbar: es gibt noch keine Fit-Punkte (Auto-Fit, Korridor- oder Bereichs-Fit ausführen).': 'Mode not available: there are no fit points yet (run auto-fit, corridor or region fit).',
    'Modus:': 'Mode:',
    'Modus: Anker setzen – Klick setzt die nähere Korridorgrenze · Esc beendet': 'Mode: set anchor – click sets the nearer corridor limit · Esc ends',
    'Modus: Ausreißer markieren – Punkt anklicken oder Kasten aufziehen · Esc beendet': 'Mode: mark outliers – click a point or drag a box · Esc ends',
    'Modus: Ausschlusszone – Rechteck aufziehen · Esc bricht ab': 'Mode: exclusion zone – drag a rectangle · Esc cancels',
    'Modus: Bereich neu fitten – Rechteck aufziehen · Esc bricht ab': 'Mode: refit region – drag a rectangle · Esc cancels',
    'Modus: Fit-Punkte im Farbplot anklicken oder per Kasten markieren → ignoriert (grau): raus aus Darstellung und ALLEN Rechnungen (insb. Kittel-Fit). Reversibel: Rückgängig und Liste im Ausreißer-Panel. Esc beendet.': 'Mode: click fit points in the color plot or mark them with a box → ignored (gray): removed from the display and ALL calculations (esp. the Kittel fit). Reversible: undo and list in the outlier panel. Esc ends.',
    'Modus: Korridor anlegen – zwei Punkte entlang der Resonanz klicken · Esc bricht ab': 'Mode: create corridor – click two points along the resonance · Esc cancels',
    'Modus: Rechteck aufziehen → Messpunkte darin werden aus allen Fits ausgenommen.': 'Mode: drag a rectangle → data points inside are excluded from all fits.',
    'Modus: Rechteck im Farbplot aufziehen → nur dort werden Fenstersuche und Fit wiederholt (löst Mehrdeutigkeiten neben der Mode auf). Optionen (Frequenz/Feld von … bis …, Modus, Fensterbreite, Resonanzen) folgen im Dialog. Funktioniert auch ohne Auto-Fit. Esc bricht ab.': 'Mode: drag a rectangle in the color plot → window search and fit are repeated only there (resolves ambiguities next to the mode). Options (frequency/field from … to …, mode, window width, resonances) follow in the dialog. Also works without auto-fit. Esc cancels.',
    'Modus: Trennlinie setzen': 'Mode: set separator',
    'Modus: Trennlinie setzen – im Linescan-Panel zwischen zwei Dips klicken (gelbe Linie ziehbar) · Esc beendet': 'Mode: set separator – click between two dips in the linescan panel (yellow line draggable) · Esc ends',
    'Modus: zwei Punkte entlang der Resonanz im Farbplot klicken → Korridor ± Breite für die nächste Mode; danach im Panel „Korridore“ den Korridor fitten. Funktioniert direkt nach dem Laden.': 'Mode: click two points along the resonance in the color plot → corridor ± width for the next mode; then fit the corridor in the “Corridors” panel. Works right after loading.',
    'M{0}': 'M{0}',
    'M{0} · Auto-Fit (Resonanz {0} je Fenster)': 'M{0} · auto-fit (resonance {0} per window)',
    'M{0} · AutoWindow (kein Korridor)': 'M{0} · AutoWindow (no corridor)',
    'M{0} · {1} Anker': 'M{0} · {1} anchors',
    'M{0}: {1} Frequenzen': 'M{0}: {1} frequencies',
    'Nachfenster (± ΔH-Vielfache):': 'Refit window (± ΔH multiples):',
    'Navigator': 'Navigator',
    'Navigator – Gesamtübersicht': 'Navigator – overview',
    'Neu fitten': 'Refit',
    'Neu gefittet f={0:.2f} GHz [{1:.3f}–{2:.3f} T] → {3} · B_res={4:.4f} T, µ₀ΔH={5:.2f} mT, R²={6:.4f}': 'Refitted f={0:.2f} GHz [{1:.3f}–{2:.3f} T] → {3} · B_res={4:.4f} T, µ₀ΔH={5:.2f} mT, R²={6:.4f}',
    'Nichts rückgängig zu machen.': 'Nothing to undo.',
    'Nichts zu wiederholen.': 'Nothing to redo.',
    'Noch keine Fits vorhanden.': 'No fits yet.',
    'Nochmal gefittet (f={0:.2f} GHz)': 'Refitted (f={0:.2f} GHz)',
    'Nur Einzelfits mit R² ≥ diesem Wert gehen in den\nKittel-/LLG-Fit ein (zusätzlich zur Problem-Einstufung).': 'Only single fits with R² ≥ this value enter the\nKittel/LLG fit (in addition to the problem classification).',
    'Nur Mode M{0}': 'Only mode M{0}',
    'Nur für die Auswertung je Mode ausgeschlossen: {0} Punkt(e) ({1}{2}) – insgesamt {3}.': 'Excluded only from the evaluation of one mode: {0} point(s) ({1}{2}) – {3} in total.',
    'Nur gefittete Frequenzen exportieren (keine Platzhalter)': 'Export fitted frequencies only (no placeholders)',
    'Nur jeden n-ten Messpunkt auswerten': 'Evaluate only every n-th data point',
    'Obere Feldgrenze des Neu-Fits (µ₀H in Tesla).': 'Upper field limit of the refit (µ₀H in tesla).',
    'Obere Frequenzgrenze des Neu-Fits.': 'Upper frequency limit of the refit.',
    'PNG (*.png);;PDF (*.pdf);;SVG (*.svg)': 'PNG (*.png);;PDF (*.pdf);;SVG (*.svg)',
    'Panel: Aktivität': 'Panel: activity',
    'Panel: Ausreißer-Liste': 'Panel: outlier list',
    'Panel: Call-Trace (Debug)': 'Panel: call trace (debug)',
    'Panel: Korridore && Zonen': 'Panel: corridors && zones',
    'Panel: Linescan-Fit': 'Panel: linescan fit',
    'Panel: Verarbeitung': 'Panel: processing',
    'Parameter: α an der Fit-Schranke': 'Parameter: α at the fit bound',
    'Parameter: α über der Plausibilitätsgrenze': 'Parameter: α above the plausibility limit',
    'Parameter: φ an der Schranke': 'Parameter: φ at the bound',
    'Physikalische Parameter': 'Physical parameters',
    'Physikalische Parameter mit 1σ-Fehlern (T und mT), alle Punkte,\nDispersions- und Linienbreitenplot.': 'Physical parameters with 1σ errors (T and mT), all points,\ndispersion and linewidth plot.',
    'Physikalische Parameter mit Fehlern (T und mT) als Excel + CSV, Plot als PNG/PDF.': 'Physical parameters with errors (T and mT) as Excel + CSV, plot as PNG/PDF.',
    'Physikalische Parameter …': 'Physical parameters …',
    'Physikalische Parameter, Verarbeitung, Anzeige- und Export-Optionen.': 'Physical parameters, processing, display and export options.',
    'Physikalische Parameter: ': 'Physical parameters: ',
    'PolderFit-Einstellungen (*{0});;JSON (*.json)': 'PolderFit settings (*{0});;JSON (*.json)',
    'PolderFit-Projekt (*.json)': 'PolderFit project (*.json)',
    'Problematische (gelb) und fehlgeschlagene (rot) Fits im Farbplot ausblenden.': 'Hide problematic (yellow) and failed (red) fits in the color plot.',
    'Problemfit ▶': 'Problem fit ▶',
    'Problemfits ausblenden': 'Hide problem fits',
    'Problemfits sind ausgeblendet und damit nicht markierbar – Ansicht → Problemfits ausblenden abschalten.': 'Problem fits are hidden and therefore cannot be marked – switch off View → Hide problem fits.',
    'Profil laden': 'Load profile',
    'Profil laden …': 'Load profile …',
    'Profil speichern': 'Save profile',
    'Profil speichern …': 'Save profile …',
    'Profil:': 'Profile:',
    'Profilname (z. B. Messrechner-Bezeichnung):': 'Profile name (e.g. name of the measurement computer):',
    'Projekt geladen ({0} Fits).': 'Project loaded ({0} fits).',
    'Projekt geladen: {0} – {1} Fits wiederhergestellt, {2} Ausreißer, {3} Zonen, {4} Korridore.': 'Project loaded: {0} – {1} fits restored, {2} outliers, {3} zones, {4} corridors.',
    'Projekt gespeichert: {0} ({1} Fits, {2} Ausreißer, {3} Zonen, {4} Korridore).': 'Project saved: {0} ({1} fits, {2} outliers, {3} zones, {4} corridors).',
    'Projekt laden': 'Load project',
    'Projekt laden …': 'Load project …',
    'Projekt speichern': 'Save project',
    'Projekt speichern …': 'Save project …',
    'Projekt, Excel/CSV, Kittel/LLG-Auswertung, Farbplot-Bild und -Matrix, TDMS und Einstellungen in einem Schritt in einen Ordner schreiben.': 'Write project, Excel/CSV, Kittel/LLG evaluation, color plot image and matrix, TDMS and settings into one folder in a single step.',
    'Projektdatei (JSON) – Sitzung fortsetzen': 'Project file (JSON) – continue session',
    'Protokoll leeren': 'Clear log',
    'Prüfe Datensatz ({0} Frequenzen) …': 'Checking data set ({0} frequencies) …',
    'Prüfen': 'Checking',
    'Punkt(e) je Mode ausgeschlossen ({0})': 'Point(s) excluded per mode ({0})',
    'Punkt(e) je Mode wieder aufgenommen ({0})': 'Point(s) re-included per mode ({0})',
    'Punktabstand Δn der Differenz-/Referenzbildung (Modulationsamplitude in\nGitterpunkten). Größer = glatter und rauschärmer, aber breitere Linien;\nkleiner = schärfer, aber verrauschter. Typisch 2–8.\nTipp: Mausrad wirkt nur, wenn das Feld den Fokus hat.': 'Point distance Δn of the difference/reference (modulation amplitude in\ngrid points). Larger = smoother and less noisy, but broader lines;\nsmaller = sharper, but noisier. Typically 2–8.\nTip: the mouse wheel only acts when the field has focus.',
    'Punkte': 'Points',
    'Quelle, Kanal-Zuordnung, Fenster, Zonen, Korridore, Ausreißer,\nBewertungen, physikalische Parameter und Verarbeitungskette.': 'Source, channel assignment, windows, zones, corridors, outliers,\nratings, physical parameters and processing chain.',
    'Re S21': 'Re S21',
    'Re S21 (Messung)': 'Re S21 (measured)',
    'Re(S21)': 'Re(S21)',
    'Rechteck im Farbplot aufziehen. Esc oder erneuter Klick bricht ab.': 'Drag a rectangle in the color plot. Esc or clicking again cancels.',
    'Rechteck: {0:.3f} – {1:.3f} T, {2:.2f} – {3:.2f} GHz.\nDort werden Fenstersuche und Fit wiederholt; Ergebnisse außerhalb bleiben unangetastet.': 'Rectangle: {0:.3f} – {1:.3f} T, {2:.2f} – {3:.2f} GHz.\nWindow search and fit are repeated there; results outside stay untouched.',
    'Referenz entlang {0}': 'Reference along {0}',
    'Referenz-Slice auf {0}': 'Reference slice on {0}',
    'Repository öffnen': 'Open repository',
    'Residuum zu gross': 'residual too large',
    'Resonanz je Frequenz automatisch suchen und fitten (mit Dialog: Frequenz/Feld von … bis …, Jumper). Mit Korridoren: jede Mode nur in ihrem Korridor. Korridor- und Bereichs-Fit funktionieren auch ohne Auto-Fit.': 'Search and fit the resonance at each frequency automatically (with dialog: frequency/field from … to …, jumper). With corridors: each mode only inside its corridor. Corridor and region fit also work without auto-fit.',
    'Resonanzen': 'Resonances',
    'Resonanzen im Korridor:': 'Resonances in corridor:',
    'Resonanzfeld $\\mu_0 H_{res}$ (T)': 'Resonance field $\\mu_0 H_{res}$ (T)',
    'Resonanzfeld & Linienbreite (T und mT), α': 'Resonance field & linewidth (T and mT), α',
    'Rot-Blau (divergierend, für derivative divide)': 'Red-blue (diverging, for derivative divide)',
    'R²-Minimum (Kittel/LLG):': 'R² minimum (Kittel/LLG):',
    'R²-Schwelle (Einzelfit):': 'R² threshold (single fit):',
    'Rückgängig': 'Undo',
    'Rückgängig (letzter Schritt)': 'Undo (last step)',
    'Rückgängig: bitte warten, ein Hintergrundprozess läuft.': 'Undo: please wait, a background process is running.',
    'Rückgängig: {0}': 'Undo: {0}',
    'Rückgängig: {0}.': 'Undone: {0}.',
    'Schließen': 'Close',
    'Schreibe Excel: {0} …': 'Writing Excel: {0} …',
    'Schreibe Kittel/LLG-Auswertung (Excel, CSV, Plot) …': 'Writing Kittel/LLG evaluation (Excel, CSV, plot) …',
    'Sekundäre R²-Schwelle der Einzelfit-Bewertung (primär zählt\ndie Mehrkriterien-Einstufung).': 'Secondary R² threshold of the single fit rating (the multi-criteria\nclassification counts first).',
    'Sichtbaren Ausschnitt des Farbplots als Bereich verwenden.': 'Use the visible region of the color plot as the range.',
    'Sitzung als JSON sichern: Quelle, Kanal-Zuordnung, Auswahl, Fenster, Zonen, Korridore, Ausreißer, Bewertungen, Parameter und Verarbeitung (nie: Zoom oder Fensterlayout).': 'Save the session as JSON: source, channel assignment, selection, windows, zones, corridors, outliers, ratings, parameters and processing (never: zoom or window layout).',
    'Spalten: ': 'Columns: ',
    'Speicher-Layout:': 'Storage layout:',
    'Speichern': 'Save',
    'Speichert nach {0}': 'Saves to {0}',
    'Sprache / Language': 'Language / Sprache',
    'Sprachwahl nicht gespeichert: {0}': 'Language choice not saved: {0}',
    'Standard-Einstellungen gespeichert: {0}': 'Default settings saved: {0}',
    'Standardwerte': 'Defaults',
    'Standardwerte wiederherstellen': 'Restore defaults',
    'Statt der Zwei-Punkt-Differenz die Mittelwerte der Fenster [i−Δn, i) und\n[i, i+Δn] vergleichen – zusätzliche Glättung (pybbfmr-Standard).': 'Instead of the two-point difference, compare the means of the windows [i−Δn, i) and\n[i, i+Δn] – additional smoothing (pybbfmr default).',
    'Statt der automatischen Fensterbreite eine feste Breite in\nFeldpunkten um das gefundene Fensterzentrum erzwingen -\nder Hebel gegen zu enge Automatik-Fenster.': 'Instead of the automatic window width, enforce a fixed width in\nfield points around the found window center -\nthe lever against automatic windows that are too narrow.',
    'Status & Bewertung': 'Status & rating',
    'Status: {0}': 'Status: {0}',
    'Stelle Fits mit gespeicherten Fenstern wieder her …': 'Restoring fits with saved windows …',
    'TDMS (*.tdms)': 'TDMS (*.tdms)',
    'TDMS gespeichert: {0}': 'TDMS saved: {0}',
    'TDMS laden': 'Load TDMS',
    'TDMS laden …': 'Load TDMS …',
    'TDMS lesen': 'Reading TDMS',
    'TDMS speichern': 'Save TDMS',
    'TDMS-Datei laden': 'Load TDMS file',
    'TDMS-Kanaele zuordnen': 'Assign TDMS channels',
    'TDMS-Quelle des Projekts': 'TDMS source of the project',
    'Temperatur': 'Temperature',
    'Temperatur (K)': 'Temperature (K)',
    'Tracing aktiv': 'Tracing active',
    'Trennlinie M{0} bei {1:.2f} GHz': 'Separator M{0} at {1:.2f} GHz',
    'Trennlinie M{0} bei {1:.2f} GHz gelöscht.': 'Separator M{0} at {1:.2f} GHz deleted.',
    'Trennlinie M{0} gelöscht': 'Separator M{0} deleted',
    'Trennlinie nicht übernommen: ein Segment hätte weniger als {0} Messpunkte – zwischen die Dips klicken.': 'Separator not applied: a segment would have fewer than {0} data points – click between the dips.',
    'Trennlinie setzen': 'Set separator',
    'Trennlinie(n) M{0} bei {1:.2f} GHz: ': 'Separator(s) M{0} at {1:.2f} GHz: ',
    'Trennlinie: zuerst im Korridor mehr als eine Resonanz vorgeben.': 'Separator: first specify more than one resonance in the corridor.',
    'Trennlinien an der angezeigten Frequenz löschen.': 'Delete the separators at the displayed frequency.',
    'Trotz Warnungen uebernehmen': 'Accept despite warnings',
    'Uebernehmen': 'Accept',
    'Umlauf: wieder beim {0} Problemfit ({1} insgesamt).': 'Wrapped around: back at the {0} problem fit ({1} in total).',
    'Unbekannter Fehler': 'Unknown error',
    'Ungefittete Frequenzen überspringen': 'Skip unfitted frequencies',
    'Unsicherheit: keine Kovarianz bestimmbar': 'Uncertainty: no covariance available',
    'Unsicherheit: u(B_res)/B_res > 2 %': 'Uncertainty: u(B_res)/B_res > 2 %',
    'Untere Feldgrenze des Neu-Fits (µ₀H in Tesla).': 'Lower field limit of the refit (µ₀H in tesla).',
    'Untere Frequenzgrenze des Neu-Fits.': 'Lower frequency limit of the refit.',
    'Untergrund (Offset, Steigung)': 'Background (offset, slope)',
    'Verarbeitete Matrix (nach Kette und Darstellung): Zeilen = Frequenzen, Spalten = Feld.': 'Processed matrix (after chain and display): rows = frequencies, columns = field.',
    'Verarbeitung (Farbplot)': 'Processing (color plot)',
    'Verarbeitung des Farbplots (divide-slice, derivative-divide, relation-amplitude, Farbskala) ein-/ausblenden – funktioniert direkt nach dem Laden, ganz ohne Fit.': 'Show/hide the color plot processing (divide-slice, derivative-divide, relation-amplitude, color scale) – works right after loading, without any fit.',
    'Verarbeitung nicht anwendbar: {0}': 'Processing not applicable: {0}',
    'Verarbeitung: {0} · Anzeige {1}': 'Processing: {0} · display {1}',
    'Verschieben: linke Maustaste ziehen\nZoomen: rechte Maustaste ziehen': 'Pan: drag with the left mouse button\nZoom: drag with the right mouse button',
    'Viridis (wahrnehmungsgleich, Standard)': 'Viridis (perceptually uniform, default)',
    'Vollbild': 'Full screen',
    'Vollbild – F11 oder Esc beendet.': 'Full screen – F11 or Esc ends.',
    'Vollbildmodus ein-/ausschalten (F11; Esc verlässt ihn).': 'Toggle full screen mode (F11; Esc leaves it).',
    'Voreinstellungen (JSON)': 'Settings (JSON)',
    'Voreinstellungen geladen: {0}': 'Settings loaded: {0}',
    'Vorgabe für das Kittel/LLG-Auswertungsfenster:\noop = Feld senkrecht zur Schicht (Gl. 2.24),\nip = Feld in der Schichtebene (Gl. 2.26).': 'Default for the Kittel/LLG evaluation window:\noop = field perpendicular to the film (eq. 2.24),\nip = field in the film plane (eq. 2.26).',
    'Vorgabe: so viele Dips liegen in diesem Korridor. Bei > 1 wird der Korridor\nje Frequenz zwischen den Dips hart getrennt (Hard Crop) und jeder Dip einzeln\ngefittet - kein Summenfit. Jeder Dip bekommt eine eigene Mode-Nummer.': 'Setting: this many dips lie in this corridor. For > 1 the corridor is split\nstrictly between the dips at each frequency (hard crop) and each dip is fitted\nseparately - no sum fit. Each dip gets its own mode number.',
    'Weiter zur Vorschau': 'Continue to preview',
    'Weiter ▶': 'Next ▶',
    'Weitere Moden (M2 …) anzeigen': 'Show further modes (M2 …)',
    'Welche Ergebnisse verwerfen? (Rückgängig: Strg+Z)': 'Which results should be discarded? (Undo: Ctrl+Z)',
    'Welche Spaltengruppen jeder Excel-/CSV-Export enthält. Die Auswahl gilt sofort und wird mit den Voreinstellungen gespeichert (Datei → Einstellungen).': 'Which column groups every Excel/CSV export contains. The selection applies immediately and is saved with the settings (File → Settings).',
    'Welche Spaltengruppen jeder Excel-/CSV-Export enthält; als Voreinstellung speicherbar.': 'Which column groups every Excel/CSV export contains; can be saved as a preset.',
    'Welche reelle Größe des (komplexen) Ergebnisses gezeichnet wird:\nBetrag, Betrag in dB, Real-/Imaginärteil oder Phase.': 'Which real quantity of the (complex) result is drawn:\nmagnitude, magnitude in dB, real/imaginary part or phase.',
    'Werkzeug „Auswählen“: Punkt anklicken schaltet ihn in die Auswahl (blauer\nRing, in beiden Plots), Kasten aufziehen fügt alle Punkte darin hinzu.\n„Auswahl ausblenden“ (Entf) schließt sie aus der Auswertung aus – auch im\nHauptfenster/Farbplot (grau; bei mehreren Moden nur für die jeweilige Mode).\nZoom/Verschieben für dichte Punktwolken; „ausgeblendete Punkte zeigen“ +\n„Auswahl einblenden“ nimmt Punkte wieder auf. Esc = Auswahl aufheben.': 'Tool “Select”: clicking a point toggles it in the selection (blue\nring, in both plots), dragging a box adds all points inside.\n“Hide selection” (Del) excludes them from the evaluation – also in the\nmain window/color plot (gray; with several modes only for the respective mode).\nZoom/pan for dense point clouds; “show hidden points” +\n“Show selection” re-includes points. Esc = clear selection.',
    'Wieder aufnehmen': 'Re-include',
    'Wiederholen': 'Redo',
    'Wiederholen: bitte warten, ein Hintergrundprozess läuft.': 'Redo: please wait, a background process is running.',
    'Wiederholen: {0}': 'Redo: {0}',
    'Wiederholt: {0}.': 'Redone: {0}.',
    'Wirksamer Status dieses Fits (Farbe/Form wie im Farbplot).': 'Effective status of this fit (color/shape as in the color plot).',
    'Wählen …': 'Choose …',
    'Zeigt live, welche polderfit-Funktionen aufgerufen werden. Nur zur Fehlersuche einschalten – das Profiling kostet Rechenzeit.': 'Shows live which polderfit functions are called. Switch on for debugging only – profiling costs computing time.',
    'Zielordner': 'Target folder',
    'Zielordner (wird bei Bedarf angelegt).': 'Target folder (created if needed).',
    'Zielordner:': 'Target folder:',
    'Zone einzeichnen': 'Draw zone',
    'Zone entfernen': 'Remove zone',
    'Zoom (Mausrad / Kästchen)': 'Zoom (mouse wheel / box)',
    'Zoom in der Übersicht per Mausrad und aufgezogenem Kästchen ein-/ausschalten (Standard aus). Doppelklick setzt den Zoom zurück; Tasten +/-/0 wirken immer.': 'Switch zoom in the overview via mouse wheel and dragged box on/off (default off). Double-click resets the zoom; keys +/-/0 always work.',
    'Zoom-Ausschnitt übernehmen': 'Use zoom region',
    'Zu wenige gute Punkte fuer den Kittel-/LLG-Fit (min. 3).': 'Too few good points for the Kittel/LLG fit (min. 3).',
    'Zum nächsten gelb/rot markierten Fit der angezeigten Mode springen\n(ignorierte Punkte werden übersprungen). Rechtsklick/Umschalt: zurück.': 'Jump to the next yellow/red fit of the displayed mode\n(ignored points are skipped). Right-click/Shift: back.',
    'Zum vorigen gelb/rot markierten Fit springen.': 'Jump to the previous yellow/red fit.',
    'Zuordnung aendern': 'Change assignment',
    'Zuordnung unvollstaendig (fehlende Pflichtrollen: {0}).': 'Assignment incomplete (missing required roles: {0}).',
    'Zurückgenommene Änderung wieder anwenden (Strg+Umschalt+Z oder Strg+Y).': 'Re-apply the undone change (Ctrl+Shift+Z or Ctrl+Y).',
    'Zusatzblätter in Excel (Einstellungen, Zonen/Korridore, Ausreißer)': 'Additional sheets in Excel (settings, zones/corridors, outliers)',
    'Zusatzoption: je Frequenz werden 1 … n Linien gefittet und das sparsamste\nModell gewählt, das die Daten erklärt (BIC). Wo weniger Dips sind, entfällt\ndie überzählige Linie. Nur Summenfit; manuelle Trennlinien haben Vorrang.\nRechenzeit etwa 2–3-fach. Aus = Verhalten wie bisher.': 'Additional option: at each frequency 1 … n lines are fitted and the most economical\nmodel that explains the data is chosen (BIC). Where there are fewer dips, the extra\nline is dropped. Sum fit only; manual separators take precedence.\nComputing time about 2–3 times. Off = behavior as before.',
    'Zwei Punkte entlang der Resonanz im Farbplot klicken → neuer Korridor\n± Breite (nächste Mode-Nummer). Esc oder erneuter Klick bricht ab.': 'Click two points along the resonance in the color plot → new corridor\n± width (next mode number). Esc or clicking again cancels.',
    'Zweiter Fit-Durchgang (Auto-/Bereichs-Fit): Fitfenster =\nB_res ± Faktor × ΔH aus dem ersten Durchgang; übernommen nur,\nwenn der Nachfit unproblematisch ist. Bis ≈ ±3 ΔH ist die\nLinienbreite fensterunabhängig; auf dem breiten Detektions-\nfenster (Faktor 8) fällt sie bei strukturiertem Untergrund\nsystematisch 5–15 % zu klein aus (Benchmark gegen LabVIEW-FTF).\n0 = aus (nur ein Durchgang auf dem Detektionsfenster).': 'Second fit pass (auto/region fit): fit window =\nB_res ± factor × ΔH from the first pass; applied only\nif the refit is unproblematic. Up to ≈ ±3 ΔH the\nlinewidth is independent of the window; on the wide detection\nwindow (factor 8) it comes out systematically 5–15 % too small\nwith structured background (benchmark against LabVIEW FTF).\n0 = off (only one pass on the detection window).',
    '[{0}/{1}] f={2:.3f} GHz │ B_res={3:.4f} T ({4:.1f} mT) │ µ₀ΔH={5:.2f} mT │ α={6:.2e} │ R²={7:.4f} │ Fenster {8} Pkt │ {9}': '[{0}/{1}] f={2:.3f} GHz │ B_res={3:.4f} T ({4:.1f} mT) │ µ₀ΔH={5:.2f} mT │ α={6:.2e} │ R²={7:.4f} │ window {8} pts │ {9}',
    '[{0}/{1}] f={2:.3f} GHz │ noch nicht gefittet – grüne Grenzen ziehen oder „Nochmal fitten“ fittet diese Frequenz │ Fenster {3} Pkt': '[{0}/{1}] f={2:.3f} GHz │ not fitted yet – dragging the green limits or “Refit” fits this frequency │ window {3} pts',
    'alle Kriterien erfüllt': 'all criteria met',
    'alle Moden': 'all modes',
    'alpha an Grenze': 'alpha at limit',
    'alpha unphysikalisch': 'alpha unphysical',
    'ausgeblendete Punkte zeigen': 'show hidden points',
    'automatisch (Kriterien)': 'automatic (criteria)',
    'automatisch (α max / 2)': 'automatic (α max / 2)',
    'automatisch aus Kanal-Laengen': 'automatic from channel lengths',
    'bestätigt': 'confirmed',
    'derivative-divide': 'derivative-divide',
    'derivative-divide: Zentraler Differenzenquotient entlang des Feldes,\ngeteilt durch den Wert in der Mitte (Maier-Flaig 2018, Gl. 4).\nBeseitigt Untergrund und Phase ohne Kalibrierung; das Ergebnis ist\nproportional zu dχ/dω. Standardansicht für die Resonanzsuche.': 'derivative-divide: central difference quotient along the field,\ndivided by the value in the middle (Maier-Flaig 2018, eq. 4).\nRemoves background and phase without calibration; the result is\nproportional to dχ/dω. Default view for the resonance search.',
    'divide-slice (Referenz-Slice)': 'divide-slice (reference slice)',
    'divide-slice: Die ganze Matrix wird durch das Spektrum bei EINEM festen\nFeldwert (Referenz-Slice) geteilt. Entfernt den frequenzabhängigen\nUntergrund (Maier-Flaig 2018, Gl. 3). Der Referenzwert sollte möglichst\nresonanzfrei sein (z. B. Rand des Feldsweeps).': 'divide-slice: the whole matrix is divided by the spectrum at ONE fixed\nfield value (reference slice). Removes the frequency-dependent\nbackground (Maier-Flaig 2018, eq. 3). The reference value should be as\nfree of resonances as possible (e.g. edge of the field sweep).',
    'entspricht:': 'corresponds to:',
    'ergänzen (nur problematische/ungefittete Fits ersetzen)': 'complete (replace only problematic/unfitted fits)',
    'f (GHz)': 'f (GHz)',
    'f = {0:.3f} GHz – nicht gefittet': 'f = {0:.3f} GHz – not fitted',
    'g-Faktor/γ, Kittel-Geometrie, Fensterbreite-Faktor, R²-Schwellen, α-Grenzen, Resonanzen je Linescan und Nachfit-Bewertung einstellen (Konvention: µ₀H in Tesla, γ = g·µ_B/ħ; Müller 2023, Kap. 2).': 'Set g-factor/γ, Kittel geometry, window width factor, R² thresholds, α limits, resonances per linescan and refit rating (convention: µ₀H in tesla, γ = g·µ_B/ħ; Müller 2023, ch. 2).',
    'g-Faktor:': 'g-factor:',
    'ganzer Feldsweep': 'whole field sweep',
    'gewichtet (GUM, w = 1/u²)': 'weighted (GUM, w = 1/u²)',
    'grüne Linien ziehen = Fenster ändern': 'drag green lines = change window',
    'gut (automatisch)': 'good (automatic)',
    'gut (vom Nutzer bestätigt)': 'good (confirmed by the user)',
    'gut bestätigen': 'confirm good',
    'gut – vom Nutzer bestätigt': 'good – confirmed by the user',
    'harte Trennung: Korridor wird je Frequenz zwischen den Dips getrennt, jeder\nDip einzeln gefittet (Nachbar-Dip abgezogen).\nSummenfit: alle Dips gemeinsam auf den Korridorpunkten, jedes B_res hart auf\nsein Segment beschränkt (gemeinsamer Untergrund).': 'hard separation: the corridor is split between the dips at each frequency, each\ndip fitted separately (neighboring dip subtracted).\nsum fit: all dips together on the corridor points, each B_res strictly limited to\nits segment (common background).',
    'ignorieren (Ausreißer)': 'ignore (outlier)',
    'ignoriert (Ausreißer)': 'ignored (outlier)',
    'je Fenster erwartet:': 'expected per window:',
    'jede ': '1 in ',
    'keine Konvergenz': 'no convergence',
    'keine Unsicherheiten': 'no uncertainties',
    'klicken = Frequenz · Kästchen ziehen = Zoom · Mausrad = rein/raus · Doppelklick = zurück · ↑/↓ · ⇧+Rad · Punkt überfahren = Fit-Info': 'click = frequency · drag box = zoom · mouse wheel = in/out · double-click = reset · ↑/↓ · ⇧+wheel · hover point = fit info',
    'löschen': 'Delete',
    'nicht gefittet': 'not fitted',
    'noch nicht gefittet': 'not fitted yet',
    'phi an Grenze': 'phi at limit',
    'problematisch': 'problematic',
    'problematisch – prüfen': 'problematic – check',
    'problematisch – vom Nutzer markiert': 'problematic – marked by the user',
    'relation-amplitude': 'relation-amplitude',
    "relation-amplitude: Jeder Slice wird durch den Nachbar-Slice im Abstand Δn\ngeteilt (divisive Untergrund-Referenz, pybbfmr 'referenced fmr').\nBetont schmale Strukturen, die sich von Slice zu Slice ändern.": "relation-amplitude: each slice is divided by the neighboring slice at distance Δn\n(divisive background reference, pybbfmr 'referenced fmr').\nEmphasizes narrow structures that change from slice to slice.",
    'sortiert/vorverarbeitet (ein Eintrag je Messpunkt)': 'sorted/preprocessed (one entry per data point)',
    'ungewichtet (Standard)': 'unweighted (default)',
    'unsortiert/roh (Matrix: je Feldschritt ein Frequenzsweep)': 'unsorted/raw (matrix: one frequency sweep per field step)',
    'verwendete Fits': 'used fits',
    'vom Nutzer als gut bestätigt': 'confirmed as good by the user',
    'vom Nutzer als problematisch markiert': 'marked as problematic by the user',
    'weitere Resonanz (Nebenmode)': 'further resonance (secondary mode)',
    'z. B. 3-5; 10.2-11': 'e.g. 3-5; 10.2-11',
    'zu wenige Punkte': 'too few points',
    '{0:.2f} GHz': '{0:.2f} GHz',
    '{0:.3f} GHz': '{0:.3f} GHz',
    '{0:.3f}–{1:.3f} T, {2:.2f}–{3:.2f} GHz': '{0:.3f}–{1:.3f} T, {2:.2f}–{3:.2f} GHz',
    '{0:.4e} rad/(s·T)': '{0:.4e} rad/(s·T)',
    '{0:.4f} T': '{0:.4f} T',
    '{0}\nFortschritt in der Statusleiste; Ergebnis am Ende': '{0}\nprogress in the status bar; result at the end',
    '{0}  ({1} Werte)': '{0}  ({1} values)',
    '{0}  {1:.0f} s': '{0}  {1:.0f} s',
    '{0}  – Abbruch angefordert, beende …': '{0}  – cancellation requested, finishing …',
    '{0} Bewertung(en) auf automatisch zurückgesetzt.': '{0} rating(s) reset to automatic.',
    '{0} Datei(en) in {1} geschrieben.': '{0} file(s) written to {1}.',
    '{0} Punkt(e) ausgewählt ({1} GHz) – Entf = ausblenden, Esc = Auswahl aufheben': '{0} point(s) selected ({1} GHz) – Del = hide, Esc = clear selection',
    '{0} Punkt(e) ignoriert.': '{0} point(s) ignored.',
    '{0} Punkt(e) je Mode wieder aufgenommen – verbleibend {1}.': '{0} point(s) re-included per mode – {1} remaining.',
    '{0} Punkt(e) wieder aufgenommen – verbleibend {1} ignoriert.': '{0} point(s) re-included – {1} still ignored.',
    '{0} bereit. Bitte eine TDMS-Datei laden.': '{0} ready. Please load a TDMS file.',
    '{0} – Abbruch angefordert, beende …': '{0} – cancellation requested, finishing …',
    '{0} – Breitband-FMR-Auswertung': '{0} – broadband FMR analysis',
    '{0} – Hilfe & Infos': '{0} – help & info',
    '{0} – das Programm arbeitet, Fortschritt in Statusleiste und Aktivität.': '{0} – the program is working, progress in the status bar and activity panel.',
    'Übernehmen': 'Apply',
    'Übersicht S21 roh · {0}': 'Overview S21 raw · {0}',
    'Übersicht S21: {0} · {1}': 'Overview S21: {0} · {1}',
    'überschreiben (alle Fits im Bereich ersetzen)': 'overwrite (replace all fits in the range)',
    'überschreiben: alle Fits im Bereich neu rechnen.\nergänzen: nur problematische oder noch nicht gefittete Frequenzen.': 'overwrite: recalculate all fits in the range.\ncomplete: only problematic or not yet fitted frequencies.',
    'Δn (Punkte):': 'Δn (points):',
    'α-Obergrenze (Einzelfit):': 'α upper limit (single fit):',
    'α-Plausibilitätsgrenze:': 'α plausibility limit:',
    'γ im Kittel-Fit festhalten (nur µ₀M_eff fitten)': 'Keep γ fixed in the Kittel fit (fit µ₀M_eff only)',
    '– manuell / Heuristik –': '– manual / heuristic –',
    '→ γ:': '→ γ:',
    '▲ problematisch': '▲ problematic',
    '◀ Problemfit': '◀ Problem fit',
    '◀ Zurück': '◀ Back',
    '◇ Nebenmode': '◇ secondary mode',
    '● gut': '● good',
    '● gut, bestätigt': '● good, confirmed',
    '● ignoriert': '● ignored',
    '⚠ Validierung: ': '⚠ Validation: ',
    '✕ fehlgeschlagen': '✕ failed',
    '⟨|S21|⟩': '⟨|S21|⟩',
    ' -> {0} von {1} Linescans': ' -> {0} of {1} linescans',
    ', γ fest': ', γ fixed',
    'jeder {0}. Feldpunkt': '1 in {0} field points',
    'jede {0}. Frequenz': '1 in {0} frequencies',
    'Betrag in dB (20·log10)': 'Magnitude in dB (20·log10)',
    'Betrag |Z|': 'Magnitude |Z|',
    'Feld {0}-{1} T': 'field {0}-{1} T',
    'Frequenz {0}-{1} GHz': 'frequency {0}-{1} GHz',
    'Imaginaerteil': 'Imaginary part',
    'Phase (Grad)': 'Phase (degrees)',
    'Realteil': 'Real part',
    'alles auswerten': 'evaluate everything',
    'automatisch bewerten': 'rate automatically',
    'bestätigen': 'confirm',
    'g={0:.4f} (γ={1:.4e} rad/(s·T)){2}, Geometrie {3}, Fensterfaktor {4:g}, R²-Schwelle {5:g}, R²-Min (Kittel) {6:g}, α max {7:g}, α plausibel {8}, Nachfenster ±{9:g}·ΔH, Kittel/LLG {10}, Nachfits {11}': 'g={0:.4f} (γ={1:.4e} rad/(s·T)){2}, geometry {3}, window factor {4:g}, R² threshold {5:g}, R² min (Kittel) {6:g}, α max {7:g}, α plausible {8}, refit window ±{9:g}·ΔH, Kittel/LLG {10}, refits {11}',
    'gewichtet': 'weighted',
    'ohne {0:g}-{1:g} GHz': 'without {0:g}-{1:g} GHz',
    'ungewichtet': 'unweighted',
    'manuell': 'manual',
    'abgebrochen': 'cancelled',
    'fertig': 'finished',
    'ersten': 'first',
    'letzten': 'last',
    'Datensatz enthaelt keine Linescans.': 'Data set contains no linescans.',
    'Feldbereich: {0:.4f} – {1:.4f} T': 'Field range: {0:.4f} – {1:.4f} T',
    'Feldpunkte je Linescan: {0} – {1}': 'Field points per linescan: {0} – {1}',
    'Frequenzachse ist nicht streng aufsteigend (Doppelungen?).': 'Frequency axis is not strictly increasing (duplicates?).',
    'Frequenzen: {0}  ({1:.3f} – {2:.3f} GHz)': 'Frequencies: {0}  ({1:.3f} – {2:.3f} GHz)',
    'Keine Auffaelligkeiten.': 'No anomalies.',
    'Mindestens ein Linescan hat nur {0} Feldpunkte (< 4) – zu wenig fuer einen Fit.': 'At least one linescan has only {0} field points (< 4) – too few for a fit.',
    'NaN-Anteil im Signal: {0:.2%}': 'NaN fraction in the signal: {0:.2%}',
    'Warnungen:': 'Warnings:',
    '{0} Linescan(s) mit konstantem Feld – Feldkanal richtig zugeordnet?': '{0} linescan(s) with constant field – field channel assigned correctly?',
    '{0} Linescan(s) mit nicht aufsteigender Feldachse.': '{0} linescan(s) with non-increasing field axis.',
    '{0} nicht-endliche Werte (NaN/Inf) in Feld/Signal ({1:.2%}).': '{0} non-finite values (NaN/Inf) in field/signal ({1:.2%}).',
}
